### ISSUE TITLE
Application vs Service 

### ISSUE THREAD

**Issue by fluffy** [coopdanger/ietf-wg-mimi#13] opened 2022-11-09 10:59 UTC
HTA raised that we use Service and Application and we should probably just use Service.

**Comment by turt2live** [comment] 2022-11-10 09:51
Duplicate of https://github.com/coopdanger/ietf-wg-mimi/issues/11 ?

**Comment by coopdanger** [comment] 2022-11-10 09:53
Duplicate of #11

**Closed** 2022-11-10 09:53 UTC
